version: "3.3"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=tortk
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=coolken123
    restart: on-failure
  tortk:
    build: .
    command: bash start.sh
    restart: on-failure
    ports:
      - "80:80"
    depends_on: 
      - db
    links:
      - db

